// <auto-generated />
namespace RecycleCoin.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_db_function_for_statistic_panel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_db_function_for_statistic_panel));
        
        string IMigrationMetadata.Id
        {
            get { return "202212042026463_mig_db_function_for_statistic_panel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
