// <auto-generated />
namespace RecycleCoin.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_sp_for_getProductsByCategoryId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_sp_for_getProductsByCategoryId));
        
        string IMigrationMetadata.Id
        {
            get { return "202211261320244_mig_sp_for_getProductsByCategoryId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
