// <auto-generated />
namespace RecycleCoin.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_keyPair : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_keyPair));
        
        string IMigrationMetadata.Id
        {
            get { return "202210241232318_mig_keyPair"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
